/*
	Mechanika
    Copyright (C) 2011 Martin Majer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * MechTextEditor.java
 *
 * Created on 3.6.2011, 9:33:24
 */

package net.martinmajer.mech;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import net.martinmajer.mech.model.*;
import java.util.*;

/**
 *
 * @author Martin
 */
public class MechTextEditor extends javax.swing.JFrame {

	private Object edited;
	private MechCanvas parent;

    /** Creates new form MechTextEditor */
    public MechTextEditor(MechCanvas parent) {
        initComponents();

		this.parent = parent;
    }

	public void setEditedObject(Object edited) {
		this.edited = edited;

		StringBuilder sb = new StringBuilder(500);

		if (edited instanceof Beam) {
			Beam beam = (Beam)edited;
			// naplníme formulář body nosníku
			for (VectorXZ p: beam.mainPoints) {
				sb.append(String.format(Locale.ENGLISH, "%.3f; %.3f;\n", p.x, p.z));
			}
			if (beam.closed) sb.append("closed;");
		}

		textArea.setText(sb.toString());
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        bottomPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();

        setTitle("Editor souřadnic");

        textPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        textPanel.setLayout(new java.awt.BorderLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new java.awt.Dimension(250, 100));

        textArea.setColumns(20);
        textArea.setFont(MechConsts.FNT_TEXT);
        textArea.setRows(5);
        scrollPane.setViewportView(textArea);

        textPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(textPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(okButton);

        cancelButton.setText("Storno");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(cancelButton);

        applyButton.setText("Použít");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(applyButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private boolean edit() {
		if (edited instanceof Beam) {
			Beam beam = (Beam)edited;



			String text = textArea.getText();
			StringTokenizer tokenizer = new StringTokenizer(text, ";");

			boolean closed = false;
			List <VectorXZ> points = new ArrayList <VectorXZ>();

			while (tokenizer.hasMoreTokens()) {
				String token1 = tokenizer.nextToken().trim();
				if (token1.equals("")) continue;
				if (token1.equals("closed")) {
					closed = true;
				}
				else {
					if (!tokenizer.hasMoreElements()) {
						Toolkit.getDefaultToolkit().beep();
						JOptionPane.showMessageDialog(this, "Zadali jste málo souřadnic!", getTitle(), JOptionPane.ERROR_MESSAGE);
						return false;
					}
					String token2 = tokenizer.nextToken().trim();

					try {
						float x = Float.parseFloat(token1);
						float z = Float.parseFloat(token2);

						points.add(new VectorXZ(x, z));
					}
					catch (NumberFormatException e) {
						Toolkit.getDefaultToolkit().beep();
						JOptionPane.showMessageDialog(this, "Chybný formát souřadnic!", getTitle(), JOptionPane.ERROR_MESSAGE);
						return false;
					}
				}
			}

			//parent.model.removeBeam(beam);

			beam.mainPoints.clear();

			for (VectorXZ point: points) {
				beam.mainPoints.add(point);
			}
			beam.reset();
			beam.closed = closed;

			parent.model.recalculate();

			parent.repaint();
			return true;
		}
		return false;
	}

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		boolean result = edit();
		if (result) setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		setVisible(false);
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
		edit();
	}//GEN-LAST:event_applyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textArea;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables

}
