/*
	Mechanika
    Copyright (C) 2011 Martin Majer

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * MechAboutDialog.java
 *
 * Created on 3.6.2011, 21:58:26
 */

package net.martinmajer.mech;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author Martin
 */
public class MechAboutDialog extends javax.swing.JDialog {

    /** Creates new form MechAboutDialog */
    public MechAboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
		info.setEditable(false);
		info.addHyperlinkListener(new HyperlinkListener() {
			public void hyperlinkUpdate(HyperlinkEvent e) {
				if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
					if (Desktop.isDesktopSupported()) {
						Desktop desktop = Desktop.getDesktop();
						if (desktop.isSupported(Desktop.Action.BROWSE)) {
							try {
								desktop.browse(e.getURL().toURI());
							}
							catch (URISyntaxException ex) {}
							catch (IOException ex) {}
						}
					}
				}
			}
		});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        info = new javax.swing.JTextPane();
        bottomPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("O programu");
        setModal(true);
        setResizable(false);

        textPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        textPanel.setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);
        scrollPane.setPreferredSize(new java.awt.Dimension(420, 220));

        info.setBackground(getBackground());
        info.setContentType("text/html");
        info.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body style=\"font-family: 'Courier New', monospace; font-size: 11pt;\">\r\n    <b style=\"font-size: 120%; background-color: Black; color: White;\">" + MechConsts.FULL_TITLE + "</b>\n    <p>Tento program vznikl jako semestrální projekt z předmětu Stavební mechanika 1A na Fakultě stavební ČVUT.</p>\n    <p>\n      Autor:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Martin Majer <br>\n      Obor:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Architektura a stavitelství, 1. ročník <br>\n      Semestr:&nbsp;&nbsp;&nbsp;&nbsp;LS 2010/2011 <br>\n      Konzultant:&nbsp;Mgr. Ing. Jaroslav Vondřejc\n    </p>\n    <p>Program je šířen pod licencí GNU General Public License v3, zdrojové kódy a další informace jsou k dispozici na:</p>\n    <p><a href=\"http://martinmajer.net/projekty/mechanika/\">http://martinmajer.net/projekty/mechanika/</a></p>\n  </body>\r\n</html>\r\n");
        scrollPane.setViewportView(info);

        textPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(textPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Zavřít");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(closeButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
		dispose();
	}//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextPane info;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables

}
